version: 2

updates:
  - package-ecosystem: npm
    directory: /
    reviewers: [querkmachine]
    schedule:
      interval: "cron"
      cronjob: "0 4 * */1 6"
    allow:
      - dependency-type: direct
      - dependency-name: caniuse-lite
    groups:
      eleventy:
        patterns:
          - "@11ty/*"
      css:
        patterns:
          - "cssnano"
          - "postcss"
          - "postcss-*"
          - "sass"
      markdown:
        patterns:
          - "markdown-*"
      linters:
        patterns:
          - "husky"
          - "lint-staged"
          - "prettier"
      utils:
        patterns:
          - "glob"
          - "highlight.js"
          - "luxon"
          - "node-html-parser"

  - package-ecosystem: github-actions
    directory: /
    reviewers: [querkmachine]
    schedule:
      interval: "cron"
      cronjob: "0 4 * */1 6"

  - package-ecosystem: github-actions
    directory: /.github/workflows/actions/install-dependencies
    reviewers: [querkmachine]
    schedule:
      interval: "cron"
      cronjob: "0 4 * */1 6"
